name: 'Issue to Project V2 Item'
description: 'Creates a Project V2 item for opened issues, to separate the issue from the card'
author: 'Florian Holzmann'
color: 'blue'
icon: 'copy'

# Define your inputs here.
inputs:
  project-url:
    required: true
    description: 'URL of the project to add issues to.'
  github-token:
    required: true
    description: 'A GitHub personal access token with write access to the project.'

# Define your outputs here.
outputs:
  project-v2-item-id:
    description: 'The Id of the created project V2 item.'

runs:
  using: node20
  main: dist/index.js
